name: Cell-1 CICD Pipeline

on:
  push:
    branches:
      - main

env:
  IMAGE_NAME: misc-common-api

jobs:
  checkout:
    runs-on: ubuntu-latest
    outputs:
      commit_sha: ${{ steps.get_sha.outputs.commit_sha }}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - id: get_sha
        name: Get Short Commit SHA
        run: echo "commit_sha=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

  integration-tests:
    runs-on: ubuntu-latest
    needs: checkout

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set Up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Run Integration Tests
        run: mvn clean verify -Pintegration-test

  build-and-push-repo:
    runs-on: ubuntu-latest
    needs: [checkout, integration-tests]

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set Up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build with Maven
        run: mvn clean package --file pom.xml

      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build and Push Docker Image
        env:
          IMAGE_NAME: ${{ env.IMAGE_NAME }}
          GIT_SHA: ${{ needs.checkout.outputs.commit_sha }}
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        run: |
          IMAGE_TAG="$DOCKER_USERNAME/$IMAGE_NAME:$GIT_SHA"
          LATEST_TAG="$DOCKER_USERNAME/$IMAGE_NAME:latest"

          echo "Building image: $IMAGE_TAG"
          docker build -t "$IMAGE_TAG" .
          docker tag "$IMAGE_TAG" "$LATEST_TAG"

          echo "Pushing images: $IMAGE_TAG and $LATEST_TAG"
          docker push "$IMAGE_TAG"
          docker push "$LATEST_TAG"
